blank_issues_enabled: false
contact_links:
    - name: 🤔 Questions and Help
      url: https://github.com/JDFED/drip-form/discussions/categories/q-a
      about: Use GitHub Discussions for unanswered questions only, requiring a maintainer's answer. Make sure the question wasn't already asked.
