name: 🤔️ Feature request
description: Suggest an idea for this project
labels:
  - enhancement
  - awaiting-approval
body:
  - type: markdown
    attributes:
      value: |
        Important things:

        - We expect you to submit a feature request including a real design (API / UI...), not just a basic idea.
        - The design does not have to be perfect, we'll discuss it and fix it if needed.

  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the feature is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you answered the question above as "no" because you feel like you could contribute directly to our repo, please check the box below. This would tell us and other people looking for contributions that someone's working on it.
        If you do check this box, please send a pull request within 7 days after a maintainer's approval so we can still delegate this to someone else.

        Note that for feature issues, we still require you to fully fill out this form and reach consensus with the maintainers on API design before rushing to implement it, so that you don't waste your time.
      options:
        - label: I'd be willing to contribute this feature to DripForm myself.
